version = "3.10.7"
runner.dialect = scala213source3
assumeStandardLibraryStripMargin = true
align.stripMargin = true
fileOverride {
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/buildSetup.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/buildDeps.mill/**" {
     runner.dialect = scala3
  }
  "glob:**/modules/traits/test/src/**" {
     runner.dialect = scala3
  }
  "glob:**/.bsp/out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
}
